name: webdav_client
description: A dart WebDAV client library, use dio as http client. * support Basic/Digest authentication * common settings * read dir * make dir * delete * rename * copy * download file * upload file * cancel request 

version: 0.0.2
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0-beta6
  xml: ^5.0.2
  meta: ^1.3.0
  convert: ^3.0.0

dev_dependencies:
  test: '>=1.0.0 <2.0.0'