name: webdav_client
description: A dart WebDAV client library,  support Basic/Digest authentication、read、make、delete、rename、copy、download、upload、cancel request 

version: 1.1.0
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  xml: ^5.1.2
  convert: ^3.0.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'